version: '2.3'
services:
  app:
    container_name: tn-api
    restart: always
    build: .
    ports:
      - '8080:8080'
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=my-secret-pw
      - DATABASE_NAME=truenorth_dev
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: tn-api-db
    image: mysql:5.7
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 2s
      timeout: 5s
      retries: 100
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: truenorth_dev
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro

volumes:
  db-data:
